services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - raven_db
    networks:
      - raven_network

  raven_db:
    image: postgres:17
    container_name: raven_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - raven_network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  raven_network:
    driver: bridge

volumes:
  db_data:
