services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      raven_db:
        condition: service_healthy
    networks:
      - raven_network
    volumes:
      - ./src:/app/src
      - ./certs:/app/certs

  raven_db:
    image: postgres:17
    container_name: raven_db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - raven_network
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  raven_network:
    driver: bridge

volumes:
  db_data:
