"""add rounds prize fields

Revision ID: 03768fc3a5fc
Revises: 055165aa633a
Create Date: 2025-05-08 14:01:53.159138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03768fc3a5fc'
down_revision: Union[str, None] = '055165aa633a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('is_prize_claimed', sa.Boolean(), nullable=False))
    op.add_column('rounds', sa.Column('prize_expires_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'prize_expires_at')
    op.drop_column('rounds', 'is_prize_claimed')
    # ### end Alembic commands ###
