"""add round min_bet_amount

Revision ID: 055165aa633a
Revises: 5c2bbca85605
Create Date: 2025-04-19 20:52:05.858305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '055165aa633a'
down_revision: Union[str, None] = '5c2bbca85605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rounds', sa.Column('min_bet_amount', sa.Integer(), nullable=False))
    sa.CheckConstraint('min_bet_amount > 0', name='check_round_min_bet_amount'),
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rounds', 'min_bet_amount')
    # ### end Alembic commands ###
