"""add sneakermodel & sneakervariant tables

Revision ID: 101f3ee0ebdb
Revises: 03a2d43c6752
Create Date: 2025-03-21 22:25:09.505597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '101f3ee0ebdb'
down_revision: Union[str, None] = '03a2d43c6752'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sneaker_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('price', sa.Float(precision=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_sneaker_models_brand'), 'sneaker_models', ['brand'], unique=False)
    op.create_index(op.f('ix_sneaker_models_type'), 'sneaker_models', ['type'], unique=False)
    op.create_table('sneaker_variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['sneaker_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sneaker_variants_model_id'), 'sneaker_variants', ['model_id'], unique=False)
    op.create_index(op.f('ix_sneaker_variants_size'), 'sneaker_variants', ['size'], unique=False)
    op.alter_column('users', 'balance',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=4),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
               existing_type=sa.Float(precision=4),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_index(op.f('ix_sneaker_variants_size'), table_name='sneaker_variants')
    op.drop_index(op.f('ix_sneaker_variants_model_id'), table_name='sneaker_variants')
    op.drop_table('sneaker_variants')
    op.drop_index(op.f('ix_sneaker_models_type'), table_name='sneaker_models')
    op.drop_index(op.f('ix_sneaker_models_brand'), table_name='sneaker_models')
    op.drop_table('sneaker_models')
    # ### end Alembic commands ###
