"""delete Float precision from sqlalchemy tables

Revision ID: 554aea3ade70
Revises: cd57584cc651
Create Date: 2025-04-04 23:43:17.390654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '554aea3ade70'
down_revision: Union[str, None] = 'cd57584cc651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'price_at_time',
                    existing_type=sa.REAL(),
                    type_=sa.Float(),
                    existing_nullable=False)
    op.alter_column('orders', 'total_amount',
                    existing_type=sa.REAL(),
                    type_=sa.Float(),
                    existing_nullable=False)
    op.alter_column('sneaker_models', 'price',
                    existing_type=sa.REAL(),
                    type_=sa.Float(),
                    existing_nullable=False)
    op.alter_column('users', 'balance',
                    existing_type=sa.REAL(),
                    type_=sa.Float(),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
                    existing_type=sa.Float(),
                    type_=sa.REAL(),
                    existing_nullable=False)
    op.alter_column('sneaker_models', 'price',
                    existing_type=sa.Float(),
                    type_=sa.REAL(),
                    existing_nullable=False)
    op.alter_column('orders', 'total_amount',
                    existing_type=sa.Float(),
                    type_=sa.REAL(),
                    existing_nullable=False)
    op.alter_column('order_items', 'price_at_time',
                    existing_type=sa.Float(),
                    type_=sa.REAL(),
                    existing_nullable=False)
    # ### end Alembic commands ###
