"""add unique constraint on user_id and round_id in bet

Revision ID: 5c2bbca85605
Revises: 92cab5c3e088
Create Date: 2025-04-19 19:18:35.330216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c2bbca85605'
down_revision: Union[str, None] = '92cab5c3e088'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_round', 'bets', ['user_id', 'round_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_round', 'bets', type_='unique')
    # ### end Alembic commands ###
