"""add sneaker_variant_id in order_items

Revision ID: adb056b7c0ec
Revises: 554aea3ade70
Create Date: 2025-04-05 21:50:55.988091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'adb056b7c0ec'
down_revision: Union[str, None] = '554aea3ade70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('sneaker_variant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'order_items', 'sneaker_variants', ['sneaker_variant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_column('order_items', 'sneaker_variant_id')
    # ### end Alembic commands ###
