"""add order and order item models

Revision ID: cd57584cc651
Revises: 06235344fd44
Create Date: 2025-03-29 20:25:24.152030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cd57584cc651'
down_revision: Union[str, None] = '06235344fd44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('order_date', sa.DateTime(timezone=True), server_default=sa.text('now()'),
                              nullable=False),
                    sa.Column('status',
                              sa.Enum('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', name='orderstatus'),
                              nullable=False),
                    sa.Column('total_amount', sa.Float(precision=4), nullable=False),
                    sa.CheckConstraint('total_amount >= 0', name='check_order_total_amount'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('order_items',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('order_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=False),
                    sa.Column('price_at_time', sa.Float(precision=10), nullable=False),
                    sa.CheckConstraint('price_at_time >= 0', name='check_order_item_price'),
                    sa.CheckConstraint('quantity > 0', name='check_order_item_quantity'),
                    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('sneaker_models', 'price',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=4),
                    existing_nullable=False)
    op.alter_column('users', 'balance',
                    existing_type=sa.REAL(),
                    type_=sa.Float(precision=4),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'balance',
                    existing_type=sa.Float(precision=4),
                    type_=sa.REAL(),
                    existing_nullable=False)
    op.alter_column('sneaker_models', 'price',
                    existing_type=sa.Float(precision=4),
                    type_=sa.REAL(),
                    existing_nullable=False)
    op.drop_table('order_items')
    op.drop_table('orders')
    # ### end Alembic commands ###
