"""sneaker variant id in order items now is not nullable

Revision ID: e3e0fefe06aa
Revises: adb056b7c0ec
Create Date: 2025-04-06 14:05:49.206580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e3e0fefe06aa'
down_revision: Union[str, None] = 'adb056b7c0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'sneaker_variant_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint('order_items_sneaker_variant_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'sneaker_variants', ['sneaker_variant_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_sneaker_variant_id_fkey', 'order_items', 'sneaker_variants',
                          ['sneaker_variant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('order_items', 'sneaker_variant_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
